// <auto-generated />
namespace CookingWithJoe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class messingwithstuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messingwithstuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201510130544182_messingwithstuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
